import turtle
t=turtle.Turtle()
t.color("dark red")
we=turtle.Screen()
we.title("shivi creation")
we.bgcolor("black")
t.pensize(5)
t.speed(4)
t.begin_fill()
t.fillcolor("dark red")
t.up()
t.goto(0,-100)
t.down()
t.left(100)
t.setheading(50)
t.fd(222)
t.circle(80,190)
t.setheading(120)
t.circle(80,180)
t.setheading(305)
t.forward(223)
t.end_fill()
t.color("dark red")
t.hideturtle()
turtle.done()
